# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearsigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='(\u6578\u5b57)\u5b78\u5e74\u5ea6\uff1a\u5e74\u5ea6+\u5b78\u671f')),
                ('title', models.CharField(max_length=50, verbose_name='\u5b78\u5e74\u5ea6\uff1a')),
                ('contact', models.ManyToManyField(to='Teacher.Parttime_Teacher')),
            ],
            options={
                'db_table': 'Yearsigned',
                'verbose_name': '\u5b78\u5e74\u5ea6\u517c\u4efb\u8001\u5e2b\u540d\u55ae',
                'verbose_name_plural': '\u4e0a\u50b3\u5b78\u5e74\u5ea6\u517c\u4efb\u8001\u5e2b\u540d\u55ae',
            },
        ),
    ]
