# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_yearsigned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearsigned',
            options={'verbose_name': '\u4e0a\u50b3\u5b78\u5e74\u5ea6\u517c\u4efb\u8001\u5e2b\u540d\u55ae', 'verbose_name_plural': '\u5b78\u5e74\u5ea6\u517c\u4efb\u8001\u5e2b\u540d\u55ae'},
        ),
    ]
