# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archeology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_year', models.IntegerField(default=1, verbose_name='\u5b78\u5e74\u5ea6')),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='\u516c\u5e03\u65e5\u671f')),
                ('file', models.FileField(blank=True, upload_to='master/file', verbose_name='\u8003\u53e4\u984c\u6a94\u68481')),
                ('file2', models.FileField(blank=True, upload_to='master/file', verbose_name='\u8003\u53e4\u984c\u6a94\u68482')),
                ('archtitle', models.CharField(max_length=50, verbose_name='\u8003\u53e4\u984c\u540d\u7a31')),
            ],
            options={
                'db_table': 'Archeology',
                'verbose_name': '\u4e0a\u50b3\u8003\u53e4\u984c',
                'verbose_name_plural': '\u8003\u53e4\u984c',
            },
        ),
    ]
