# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_archeology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.IntegerField(choices=[(1, '\u6559\u5b78\u78a9\u58eb\u73ed\u5b78\u4f4d\u8003\u8a66\u76f8\u95dc\u6a94\u6848\u4e0b\u8f09'), (2, '\u6559\u5b78\u78a9\u58eb\u73ed\u7814\u7a76\u8a08\u756b\u53e3\u8a66\u76f8\u95dc\u6a94\u6848'), (3, '\u6559\u5b78\u78a9\u58eb\u73ed\u8ad6\u6587\u53e3\u8a66\u76f8\u95dc\u6a94\u6848')], verbose_name='\u6a94\u6848\u985e\u5225')),
            ],
            options={
                'db_table': 'Teachemaster',
                'verbose_name': '\u4e0a\u50b3\u6559\u5b78\u78a9\u58eb\u73ed\u8868\u683c',
                'verbose_name_plural': '\u6559\u5b78\u78a9\u58eb\u73ed\u8868\u683c',
            },
        ),
        migrations.CreateModel(
            name='Teachemaster_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Master.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachmaster', to='Master.Teachemaster')),
            ],
            options={
                'db_table': 'Teachemaster_Upload',
                'verbose_name': '\u6559\u5b78\u78a9\u58eb\u73ed\u8868\u683c\u6a94\u6848',
            },
            bases=('Master.upload_file',),
        ),
    ]
