# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBachelor_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetitle', models.IntegerField(choices=[(1, '\u5b78\u4f4d\u8003\u8a66\u76f8\u95dc\u6a94\u6848\u4e0b\u8f09'), (2, '\u7814\u7a76\u8a08\u756b\u53e3\u8a66\u76f8\u95dc\u6a94\u6848'), (3, '\u8ad6\u6587\u53e3\u8a66\u76f8\u95dc\u6a94\u6848')], verbose_name='\u6a94\u6848\u985e\u5225')),
            ],
            options={
                'db_table': 'NBachelor_Test',
                'verbose_name': '\u4e0a\u50b3\u5b78\u4f4d\u8003\u8a66\u8868\u683c',
                'verbose_name_plural': '\u5b78\u4f4d\u8003\u8a66\u8868\u683c\u4e0b\u8f09',
            },
        ),
        migrations.CreateModel(
            name='NCourse_Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField(max_length=300, verbose_name='\u7279\u8272\u7c21\u4ecb')),
                ('architecture', models.TextField(max_length=300, verbose_name='\u8ab2\u7a0b\u67b6\u69cb')),
            ],
            options={
                'db_table': 'NCourse_Architectur',
                'verbose_name': '\u4e0a\u50b3\u8ab2\u7a0b\u67b6\u69cb\u3002\u4fee\u696d\u8981\u9ede',
                'verbose_name_plural': '\u8ab2\u7a0b\u67b6\u69cb\u3002\u4fee\u696d\u8981\u9ede',
            },
        ),
        migrations.CreateModel(
            name='NSeminar_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6a19\u984c\u540d\u7a31')),
                ('file1', models.FileField(blank=True, upload_to='masternight/file', verbose_name='\u9644\u4ef6\u6a94\u68481')),
                ('file2', models.FileField(blank=True, upload_to='masternight/file', verbose_name='\u9644\u4ef6\u6a94\u68482')),
                ('link', models.URLField(verbose_name='\u9023\u7d50')),
            ],
            options={
                'db_table': 'NSeminar_Information',
                'verbose_name': '\u4e0a\u50b3\u7814\u8a0e\u6703\u8cc7\u8a0a',
                'verbose_name_plural': '\u7814\u8a0e\u6703\u8cc7\u8a0a',
            },
        ),
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='masternight/file', verbose_name='\u9644\u4ef6\u6a94\u68481')),
                ('file2', models.FileField(blank=True, upload_to='masternight/file', verbose_name='\u9644\u4ef6\u6a94\u68482')),
                ('filename', models.CharField(max_length=50, verbose_name='\u9644\u4ef6\u6a94\u6848\u540d\u7a31')),
            ],
        ),
        migrations.CreateModel(
            name='NBachelor_Test_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Masternight.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nbachelor', to='Masternight.NBachelor_Test')),
            ],
            options={
                'db_table': 'NBachelor_Test_Upload',
                'verbose_name': '\u5b78\u4f4d\u8003\u8a66\u8868\u683c\u6a94\u6848',
            },
            bases=('Masternight.upload_file',),
        ),
        migrations.CreateModel(
            name='NCourse_Architecture_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Masternight.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncourse', to='Masternight.NCourse_Architecture')),
            ],
            options={
                'db_table': 'NCourse_Architecture_Upload',
                'verbose_name_plural': '\u8ab2\u7a0b\u67b6\u69cb\u3002\u4fee\u696d\u8981\u9ede\u6a94\u6848',
            },
            bases=('Masternight.upload_file',),
        ),
    ]
