# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magzine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.IntegerField(choices=[(1, '\u300a\u5357\u5927\u9ad4\u80b2\u5b78\u5831\u300b\uff08\u65b0\u7248\u520a\u7269\uff09\u6982\u89bd'), (2, '\u300a\u5357\u5927\u9ad4\u80b2\u5b78\u5831\u300b\uff08\u820a\u7248\u520a\u7269\uff09\u6982\u89bd')], verbose_name='\u6a94\u6848\u985e\u5225')),
                ('filetitle', models.CharField(max_length=50, verbose_name='\u520a\u7269\u540d\u7a31')),
                ('file', models.FileField(blank=True, upload_to='sportmagzine/magzine', verbose_name='\u520a\u7269\u4e0a\u50b31:')),
                ('file2', models.FileField(blank=True, upload_to='sportmagzine/magzine', verbose_name='\u520a\u7269\u4e0a\u50b32:')),
            ],
            options={
                'db_table': 'Magzine',
                'verbose_name': '\u4e0a\u50b3\u520a\u7269\u5167\u5bb9',
                'verbose_name_plural': '\u9ad4\u80b2\u5b78\u5831\u520a\u7269',
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(max_length=500, verbose_name='\u9ad4\u80b2\u5b78\u5831\u4e3b\u984c')),
            ],
            options={
                'db_table': 'Regulation',
                'verbose_name': '\u4e0a\u50b3\u9ad4\u80b2\u5b78\u5831\u5be9\u67e5\u5167\u5bb9',
                'verbose_name_plural': '\u9ad4\u80b2\u5b78\u5831\u5be9\u67e5\u5167\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='\u6a94\u6848\u6a19\u984c\u540d\u7a31')),
                ('file1', models.FileField(blank=True, upload_to='sportmagzine/file', verbose_name='\u9644\u4ef6\u6a94\u68481')),
                ('file2', models.FileField(blank=True, upload_to='sportmagzine/file', verbose_name='\u9644\u4ef6\u6a94\u68481')),
            ],
        ),
        migrations.CreateModel(
            name='Regulation_Upload',
            fields=[
                ('uploadfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SportMagzine.UploadFile')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation', to='SportMagzine.Regulation')),
            ],
            options={
                'db_table': 'Regulation_Upload',
                'verbose_name_plural': '\u76f8\u95dc\u6a94\u6848\u95b1\u89bd\u8207\u4e0b\u8f09',
            },
            bases=('SportMagzine.uploadfile',),
        ),
    ]
