# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u6d3b\u52d5\u65e5\u671f')),
                ('name', models.CharField(max_length=100, verbose_name='\u6d3b\u52d5\u540d\u7a31')),
                ('speaker', models.CharField(blank=True, max_length=50, verbose_name='\u6f14\u8b1b\u8005')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='\u5730\u9ede')),
            ],
            options={
                'db_table': 'AcademicActivities',
                'verbose_name': '\u4e0a\u50b3\u6d3b\u52d5\u5167\u5bb9',
                'verbose_name_plural': '\u6d3b\u52d5\u5167\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='AcademicObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='\u5b78\u5e74\u5ea6')),
                ('filetitle', models.CharField(choices=[('\u7814\u8a0e\u6703\u8207\u7814\u7fd2', '\u7814\u8a0e\u6703\u8207\u7814\u7fd2'), ('\u5c08\u984c\u6f14\u8b1b', '\u5c08\u984c\u6f14\u8b1b'), ('\u9ad4\u80b2\u8868\u6f14\u6703', '\u9ad4\u80b2\u8868\u6f14\u6703')], max_length=10, verbose_name='\u6a94\u6848\u985e\u5225')),
            ],
            options={
                'db_table': 'AcademicObjects',
                'verbose_name': '\u4e0a\u50b3\u6d3b\u52d5\u5e74\u5ea6\u8207\u9805\u76ee\u914d\u7f6e',
                'verbose_name_plural': '\u6d3b\u52d5\u5e74\u5ea6\u8207\u9805\u76ee\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Upload_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/image', verbose_name='\u7167\u7247\u4e0a\u50b3')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicUpload',
            fields=[
                ('upload_image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Activities.Upload_Image')),
            ],
            options={
                'db_table': 'AcademicUpload',
                'verbose_name': '\u6d3b\u52d5\u7167\u7247',
            },
            bases=('Activities.upload_image',),
        ),
        migrations.AddField(
            model_name='academicactivities',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Activities.AcademicObjects'),
        ),
        migrations.AddField(
            model_name='academicupload',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicimage', to='Activities.AcademicActivities'),
        ),
    ]
