# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u699c\u55ae\u540d\u7a31')),
                ('discription', models.TextField(max_length=800, verbose_name='\u8aaa\u660e(\u5305\u542b\u5831\u5230\u7b49)')),
            ],
            options={
                'db_table': 'List',
                'verbose_name_plural': '\u5404\u9805\u8003\u8a66\u699c\u55ae',
            },
        ),
        migrations.CreateModel(
            name='Master_Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='\u6a19\u984c(\u5b78\u5e74\u5ea6)\uff1a')),
                ('created_time', models.CharField(max_length=10, verbose_name='\u5b78\u5e74\u5ea6(\u6578\u5b57)\uff1a')),
            ],
            options={
                'db_table': 'Master_Admission',
                'verbose_name': '\u4e0a\u50b3\u78a9\u58eb\u73ed\u62db\u751f\u8cc7\u8a0a',
                'verbose_name_plural': '\u78a9\u58eb\u73ed\u62db\u751f',
            },
        ),
        migrations.CreateModel(
            name='Master_night2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='\u6a19\u984c(\u5b78\u5e74\u5ea6)\uff1a')),
                ('created_time', models.CharField(max_length=10, verbose_name='\u5b78\u5e74\u5ea6(\u6578\u5b57)\uff1a')),
            ],
            options={
                'db_table': 'Master_night2',
                'verbose_name': '\u4e0a\u50b3\u78a9\u5c08\u73ed\u62db\u751f\u8cc7\u8a0a',
                'verbose_name_plural': '\u78a9\u5c08\u73ed\u62db\u751f',
            },
        ),
        migrations.CreateModel(
            name='Senior_Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6a19\u984c(\u5b78\u5e74\u5ea6)\uff1a')),
            ],
            options={
                'db_table': 'Senior_Admission',
                'verbose_name': '\u4e0a\u50b3\u9ad8\u4e2d\u751f\u7533\u8acb\u5165\u5b78\u8cc7\u8a0a',
                'verbose_name_plural': '\u9ad8\u4e2d\u751f\u7533\u8acb\u5165\u5b78',
            },
        ),
        migrations.CreateModel(
            name='Senior_Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6a19\u984c(\u5b78\u5e74\u5ea6)\uff1a')),
            ],
            options={
                'db_table': 'Senior_Distribution',
                'verbose_name': '\u4e0a\u50b3\u5927\u5b78\u8003\u8a66\u5165\u5b78\u5206\u767c',
                'verbose_name_plural': '\u5927\u5b78\u8003\u8a66\u5165\u5b78\u5206\u767c',
            },
        ),
        migrations.CreateModel(
            name='Sport_Excellent_Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='\u6a19\u984c(\u5b78\u5e74\u5ea6)\uff1a')),
                ('created_time', models.CharField(max_length=10, verbose_name='\u5b78\u5e74\u5ea6(\u6578\u5b57)')),
            ],
            options={
                'db_table': 'Sport_Excellent_Admission',
                'verbose_name': '\u4e0a\u50b3\u904b\u52d5\u7e3e\u512a\u55ae\u7368\u62db\u751f',
                'verbose_name_plural': '\u904b\u52d5\u7e3e\u512a\u55ae\u7368\u62db\u751f',
            },
        ),
        migrations.CreateModel(
            name='Traffic_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '\u81fa\u5357\u5927\u5b78\u4ea4\u901a\u8cc7\u8a0a\uff08\u5e9c\u57ce\u6821\u5340\uff09'), (2, '\u81fa\u5357\u5927\u5b78\u4ea4\u901a\u8cc7\u8a0a\uff08\u69ae\u8b7d\u6559\u5b78\u4e2d\u5fc3\uff09')], verbose_name='\u53f0\u5357\u5927\u5b78\u6821\u5340(\u4ea4\u901a)\uff1a')),
            ],
            options={
                'db_table': 'Traffic_Information',
                'verbose_name': '\u4e0a\u50b3\u4ea4\u901a\u8cc7\u8a0a',
                'verbose_name_plural': '\u4ea4\u901a\u8cc7\u8a0a',
            },
        ),
        migrations.CreateModel(
            name='Traffic_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='\u4ea4\u901a\u65b9\u6cd5')),
                ('process', models.TextField(blank=True, max_length=250, verbose_name='\u4ea4\u901a\u904e\u7a0b')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trafmeth', to='RecruStu.Traffic_Information')),
            ],
            options={
                'db_table': 'Traffic_Method',
                'verbose_name_plural': '\u5230\u9054\u65b9\u6cd5',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='\u8f49\u5b78\u8003\u62db\u751f\u6a19\u984c')),
                ('place', models.TextField(blank=True, max_length=100, verbose_name='\u62db\u751f\u540d\u984d')),
                ('commonsubject', models.TextField(blank=True, max_length=50, verbose_name='\u5171\u540c\u79d1\u76ee')),
                ('profesubject', models.TextField(blank=True, max_length=150, verbose_name='\u5c08\u696d\u79d1\u76ee')),
                ('achievement', models.TextField(blank=True, max_length=150, verbose_name='\u6210\u7e3e\u63a1\u8a08\u65b9\u5f0f')),
                ('order', models.TextField(blank=True, max_length=150, verbose_name='\u540c\u5206\u9304\u53d6\u9806\u5e8f')),
            ],
            options={
                'db_table': 'Transfer_Test',
                'verbose_name': '\u4e0a\u50b3\u8f49\u5b78\u8003\u8cc7\u6599',
                'verbose_name_plural': '\u8f49\u5b78\u8003',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Test_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Transfer_Test_Detail',
                'verbose_name_plural': '\u8f49\u5b78\u8003\u7d30\u9805\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Test_Detail2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=50, verbose_name='\u6e2c\u9a57\u9805\u76ee')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='\u6e2c\u9a57\u8aaa\u660e')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transtestdetail2', to='RecruStu.Transfer_Test_Detail')),
            ],
            options={
                'db_table': 'Transfer_Test_Detail2',
                'verbose_name_plural': '\u8f49\u5b78\u8003\u7d30\u9805\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Test_mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u6e2c\u9a57\u540d\u7a31')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transtestm', to='RecruStu.Transfer_Test')),
            ],
            options={
                'db_table': 'Transfer_Test_mode',
                'verbose_name_plural': '\u8f49\u5b78\u8003\u6e2c\u9a57\u9805\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, upload_to='recrustu/file', verbose_name='\u9644\u4ef6\u6a94\u68481:')),
                ('file2', models.FileField(blank=True, upload_to='recrustu/file', verbose_name='\u9644\u4ef6\u6a94\u68482:')),
                ('filename', models.CharField(blank=True, max_length=50, verbose_name='\u9644\u4ef6\u6a94\u6848\u540d\u7a31')),
            ],
        ),
        migrations.CreateModel(
            name='List_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecruStu.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listupload', to='RecruStu.List')),
            ],
            options={
                'db_table': 'List_Upload',
                'verbose_name_plural': '\u699c\u55ae\u8cc7\u6599',
            },
            bases=('RecruStu.upload_file',),
        ),
        migrations.CreateModel(
            name='Master_Admission_Test',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecruStu.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastertest', to='RecruStu.Master_Admission')),
            ],
            options={
                'db_table': 'Master_Admission_Test',
                'verbose_name_plural': '\u78a9\u58eb\u73ed\u5165\u5b78\u8003\u8a66',
            },
            bases=('RecruStu.upload_file',),
        ),
        migrations.CreateModel(
            name='Master_Audition',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecruStu.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteraudi', to='RecruStu.Master_Admission')),
            ],
            options={
                'db_table': 'Master_Audition',
                'verbose_name_plural': '\u78a9\u58eb\u73ed\u7504\u8a66',
            },
            bases=('RecruStu.upload_file',),
        ),
        migrations.CreateModel(
            name='MasterNight_Audition2',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecruStu.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastnighaudi', to='RecruStu.Master_night2')),
            ],
            options={
                'db_table': 'MasterNight_Audition2',
                'verbose_name_plural': '\u78a9\u5c08\u73ed\u7504\u8a66',
            },
            bases=('RecruStu.upload_file',),
        ),
        migrations.CreateModel(
            name='Seninor2_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecruStu.Upload_File')),
                ('image', models.ImageField(blank=True, upload_to='recrustu/image', verbose_name='\u7167\u7247\u4e0a\u50b3')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seninor2up', to='RecruStu.Senior_Distribution')),
            ],
            options={
                'db_table': 'Seninor2_Upload',
                'verbose_name_plural': '\u5927\u5b78\u8003\u8a66\u5165\u5b78\u6a94\u6848',
            },
            bases=('RecruStu.upload_file',),
        ),
        migrations.CreateModel(
            name='Seninor_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecruStu.Upload_File')),
                ('image', models.ImageField(blank=True, upload_to='recrustu/image', verbose_name='\u7167\u7247\u4e0a\u50b3')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seninorup', to='RecruStu.Senior_Admission')),
            ],
            options={
                'db_table': 'Seninor_Upload',
                'verbose_name_plural': '\u9ad8\u4e2d\u7533\u8acb\u5165\u5b78\u6a94\u6848',
            },
            bases=('RecruStu.upload_file',),
        ),
        migrations.CreateModel(
            name='Sport_Admission_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecruStu.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportad', to='RecruStu.Sport_Excellent_Admission')),
            ],
            options={
                'db_table': 'Sport_Admission_Upload',
                'verbose_name_plural': '\u4e0a\u50b3\u62db\u751f\u8a0a\u606f',
            },
            bases=('RecruStu.upload_file',),
        ),
        migrations.CreateModel(
            name='Transfer_Test_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecruStu.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transtestu', to='RecruStu.Transfer_Test')),
            ],
            options={
                'db_table': 'Transfer_Test_Upload',
                'verbose_name_plural': '\u8f49\u5b78\u8003\u6a94\u6848',
            },
            bases=('RecruStu.upload_file',),
        ),
        migrations.AddField(
            model_name='transfer_test_detail',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transtestdetail', to='RecruStu.Transfer_Test_mode'),
        ),
    ]
