# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruStu', '0002_auto_20170426_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_test_detail2',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='transfer_test_mode',
            name='contact',
        ),
        migrations.AddField(
            model_name='transfer_test_detail',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='\u6e2c\u9a57\u8aaa\u660e'),
        ),
        migrations.AddField(
            model_name='transfer_test_detail',
            name='project',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6e2c\u9a57\u9805\u76ee'),
        ),
        migrations.AlterField(
            model_name='transfer_test_detail',
            name='contact',
            field=models.ManyToManyField(related_name='transtestdetail', to='RecruStu.Transfer_Test'),
        ),
        migrations.DeleteModel(
            name='Transfer_Test_Detail2',
        ),
        migrations.DeleteModel(
            name='Transfer_Test_mode',
        ),
    ]
