# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruStu', '0003_auto_20170426_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_test_detail',
            name='contact',
        ),
        migrations.AddField(
            model_name='transfer_test',
            name='contact',
            field=models.ManyToManyField(related_name='transtestdetail', to='RecruStu.Transfer_Test_Detail'),
        ),
    ]
