# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actitle', models.CharField(max_length=100, verbose_name='\u76f8\u95dc\u9023\u7d50\u540d\u7a31')),
                ('actlink', models.URLField(blank=True, verbose_name='\u9023\u7d50')),
                ('actimage', models.ImageField(upload_to='activitynews/image', verbose_name='\u5716\u7247')),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='\u516c\u5e03\u65e5\u671f')),
            ],
            options={
                'db_table': 'Linkact',
                'verbose_name': '\u4e0a\u50b3\u76f8\u95dc\u9023\u7d50',
                'verbose_name_plural': '\u76f8\u95dc\u9023\u7d50',
            },
        ),
        migrations.CreateModel(
            name='Linkindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100, verbose_name='\u76f8\u95dc\u6c42\u8077\u8a0a\u606f\u6a19\u984c')),
                ('link', models.URLField(blank=True, verbose_name='\u6c42\u8077\u9023\u7d50')),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='\u516c\u5e03\u65e5\u671f')),
            ],
            options={
                'db_table': 'Linkindex',
                'verbose_name': '\u4e0a\u50b3\u6c42\u8077\u8a0a\u606f',
                'verbose_name_plural': '\u6c42\u8077\u8a0a\u606f',
            },
        ),
    ]
