# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityNews', '0002_linkactivity_linkindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkactivity',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u516c\u5e03\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='linkindex',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u516c\u5e03\u65e5\u671f'),
        ),
    ]
