# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityNews', '0003_auto_20170418_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkactivity',
            name='image',
            field=models.ImageField(default=True, upload_to='activitynews/image', verbose_name='\u4ee3\u8868\u5716\u7247'),
        ),
    ]
