# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniAccociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='\u6a19\u984c')),
                ('headline', models.CharField(max_length=100, verbose_name='\u5927\u6a19\u984c')),
                ('sitetitle', models.CharField(max_length=100, verbose_name='\u5074\u6a19')),
            ],
            options={
                'db_table': 'AlumniAccociation',
                'verbose_name': '\u4e0a\u50b3\u7cfb\u53cb\u6703',
                'verbose_name_plural': '\u7cfb\u53cb\u6703',
            },
        ),
        migrations.CreateModel(
            name='AlumniAccociation_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6a19\u984c')),
                ('content', models.TextField(max_length=2000, verbose_name='\u5167\u5bb9')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='Others.AlumniAccociation')),
            ],
            options={
                'db_table': 'AlumniAccociation_Upload',
                'verbose_name_plural': '\u7cfb\u53cb\u6703\u7d30\u9805',
            },
        ),
        migrations.CreateModel(
            name='Honorannounce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='\u69ae\u8b7d\u699c\u5167\u5bb9')),
            ],
            options={
                'db_table': 'Honorannounce',
                'verbose_name': '\u4e0a\u50b3\u69ae\u8b7d\u699c',
                'verbose_name_plural': '\u69ae\u8b7d\u699c',
            },
        ),
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='others/file', verbose_name='\u6a94\u6848\u4e0a\u50b3')),
                ('filename', models.CharField(blank=True, max_length=100, verbose_name='\u6a94\u6848\u540d\u7a31')),
            ],
        ),
        migrations.CreateModel(
            name='Honorannounce_Upload',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Others.Upload_File')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor', to='Others.Honorannounce')),
            ],
            options={
                'db_table': 'Honorannounce_Upload',
                'verbose_name_plural': '\u69ae\u8b7d\u699c\u6a94\u6848',
            },
            bases=('Others.upload_file',),
        ),
        migrations.CreateModel(
            name='StuAccociation',
            fields=[
                ('upload_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Others.Upload_File')),
                ('file2', models.FileField(blank=True, upload_to='others/file', verbose_name='\u6a94\u6848\u4e0a\u50b32')),
            ],
            options={
                'db_table': 'StuAccociation',
                'verbose_name': '\u4e0a\u50b3\u7cfb\u5b78\u6703',
                'verbose_name_plural': '\u7cfb\u5b78\u6703',
            },
            bases=('Others.upload_file',),
        ),
    ]
